id: P7DC16D7E
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Lodrö Rinchen
  language: en
  description: 'Texts by Khenchen Ngawang Lodrö Rinchen (mkhan chen ngag dbang blo
    gros rin chen, 1892–1952):'
  volume:
    b46e7c7072cd462b8e6488b74dfd8768:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
created_at: '2022-03-01T00:21:03.086613'
last_modified_at: '2022-03-01T00:21:03.086621'
